#!/usr/bin/env bash

[[ -f ~/.git-prompt.sh ]] && source ~/.git-prompt.sh
[[ $(type -t __git_ps1) == function ]] && GIT_BRANCH=$(__git_ps1 " (%s)") || GIT_BRANCH=""
[[ -x "$(command -v rg)" ]] && FZF_DEFAULT_COMMAND='rg --sort-files --files --hidden -g "!.git"'

FILE="$(fzf --ansi --prompt="$PWD$GIT_BRANCH > " --height 100% --margin 0% --reverse --info=hidden --header-first)"
[[ -z "$FILE" ]] && exit 1
echo "${PWD}/${FILE}" > /tmp/vim_fuzzy_current_file
