#!/usr/bin/env bash


cat 2>/dev/null > $HOME/.vim/coc-settings.json <<-EOF
{
    // GENERAL CONFIG
    "coc.preferences.extensionUpdateCheck": "weekly",
    "session.directory": "~/.vim/sessions",
    "inlayHint.enable": false,

    // COC-DIAGNOSTICS
    "diagnostic.messageTarget":"echo",
    "diagnostic.virtualText": true,
    "diagnostic.virtualTextCurrentLineOnly": false,

    // COC-JAVA CONFIG
    "java.project.referencedLibraries": ["~/.vim/gson-2.10.jar"]
}
EOF
