#!/usr/bin/env bash

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

hc() { herbstclient "$@" ; }
hc emit_hook reload
xsetroot -solid '#0000EE'




## KEYBINDS
###########

hc keyunbind --all
Mod=Mod4
Term="st"
Shell="bash"

hc keybind $Mod-Shift-c close
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload

# my programs
hc keybind $Mod-Shift-x spawn xkill
hc keybind $Mod-Return  spawn $Term
hc keybind Alt-Return   spawn dm-run
hc keybind Alt-q        spawn dm-quit
hc keybind Alt-s        spawn $SCRIPTPATH/hlwm-scratch

# focusing clients
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right

# moving clients
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# tags
tag_names=( {1..9} 0 )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true

for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# layouting
hc keybind $Mod-i split explode
hc keybind $Mod-u remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-a attr clients.focus.floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-w                                                    \
            or , and . compare tags.focus.curframe_wcount = 2        \
                     . cycle_layout +1 vertical horizontal max grid  \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-e         jumpto urgent
hc keybind $Mod-Up        use_index +1
hc keybind $Mod-Down      use_index -1
hc keybind $Mod-Right     use_index +1 --skip-visible
hc keybind $Mod-Left      use_index -1 --skip-visible
hc keybind $Mod-Tab       cycle_frame +1
hc keybind $Mod-BackSpace use_previous
hc keybind Alt-Tab        cycle +1
hc keybind Alt-BackSpace  cycle_monitor

# special keys
hc keybind XF86MonBrightnessUp   spawn xbacklight -inc 10
hc keybind XF86MonBrightnessDown spawn xbacklight -dec 10
hc keybind XF86AudioRaiseVolume  spawn chvol up
hc keybind XF86AudioLowerVolume  spawn chvol down
hc keybind XF86AudioMute         spawn chvol mute
hc keybind XF86AudioPrev         spawn playerctl previous
hc keybind XF86AudioNext         spawn playerctl next
hc keybind XF86AudioPlay         spawn playerctl play-pause




## THEME
########

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#5C5CFF'
hc set frame_border_normal_color '#7F7F7F'
hc set frame_bg_active_color '#5C5CFF'
hc set frame_bg_normal_color '#7F7F7F'
hc set frame_border_width 2
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_padding -2
hc set focus_follows_mouse 0

hc attr theme.active.color '#5C5CFF'
hc attr theme.normal.color '#7F7F7F'
hc attr theme.urgent.color '#FF0000'
hc attr theme.inner_width 0
hc attr theme.outer_width 0
hc attr theme.inner_color '#E5E5E5'
hc attr theme.outer_color '#E5E5E5'
hc attr theme.border_width 2
hc attr theme.floating.border_width 2
hc attr theme.floating.inner_width 0
hc attr theme.floating.outer_width 0
hc attr theme.floating.inner_color '#E5E5E5'
hc attr theme.floating.outer_color '#E5E5E5'
hc attr theme.active.inner_color '#5C5CFF'
hc attr theme.active.outer_color '#5C5CFF'
hc attr theme.background_color '#E5E5E5'

hc set frame_gap 10
hc set window_gap 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0
hc set focus_crosses_monitor_boundaries 1
hc set swap_monitors_to_get_tag 1




## RULES
########

hc unrule -F
hc rule focus=on
hc rule floatplacement=center  # smart,center,none
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off




## TREE STYLES
##############

# '╾│ ├└╼─┐'
# '╾│ ├╰╼─╮'
# '*| +`>-.'
# '*| +`-->'

herbstclient set tree_style '╾│ ├└╼─┐'
hc unlock




## KEYLAYOUT
############

setxkbmap -layout it  # gb,it,us
xmodmap ~/.Xmodmap




## SXHKD, MONITORS, POLYBAR, WALLPAPER, PICOM, SYSICONS
#######################################################

$SCRIPTPATH/hlwm-sxhkd
$SCRIPTPATH/hlwm-polybar $($SCRIPTPATH/hlwm-monitor)
$SCRIPTPATH/hlwm-wallpaper
$SCRIPTPATH/hlwm-sysicons
