#!/usr/bin/env bash

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
export LOCATION=$(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | awk 'OFS=":" {print $3,$5}' | tr -d ',}')

[[ -x "$(command -v nm-applet)" && $(/usr/bin/ps -e | grep nm-applet | wc -l) -eq 0 ]] && nm-applet &
[[ -x "$(command -v blueman-applet)" && $(/usr/bin/ps -e | grep blueman-applet | wc -l) -eq 0 ]] && blueman-applet &
[[ -x "$(command -v redshift-gtk)" && $(/usr/bin/ps -e | grep redshift-gtk | wc -l) -eq 0 ]] && redshift-gtk -l $LOCATION -Pr -t 8000:5000 &
