#!/usr/bin/env bash

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

if [[ -x "$(command -v sxhkd)" ]]; then
    killall -q sxhkd
    while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
    sxhkd -c $SCRIPTPATH/sxhkdrc &
fi
