#!/usr/bin/env bash

source $HOME/.xinput.bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


### XDG autostart, loginctl lock-session, applets
#################################################

[[ -x "$(command -v dex)" ]] && dex --autostart --environment i3 &
[[ -x "$(command -v lxpolkit)" ]] && lxpolkit &
[[ -x "$(command -v nm-applet)" ]] && nm-applet &
[[ -x "$(command -v blueman-applet)" ]] && blueman-applet &
[[ -x "$(command -v flameshot)" ]] && flameshot &
[[ -x "$(command -v xautolock)" ]] && xautolock -time 15 -locker slock &




### Load monitor config as single/dual with autorandr
#####################################################

NMON=$(xrandr --query | grep " connected" | cut -d" " -f1 | wc -l)
[[ $NMON -eq 1 ]] && autorandr --load master
[[ $NMON -eq 2 ]] && autorandr --load dual

[[ -f ~/.fehbg ]] && PIC=$(awk 'FNR==2 {print $4}' ~/.fehbg)
if [[ -n $PIC && -f ${PIC:1:-1} ]]; then
    ~/.fehbg
else
    feh --bg-fill "$SCRIPTPATH/default.png"
fi




### Touchpad properties (xinput list-props "$TOUCHPADID")
#########################################################

xinput set-prop "$TOUCHPADID" "libinput Tapping Enabled" 1
xinput set-prop "$TOUCHPADID" "libinput Tapping Drag Enabled" 1
xinput set-prop "$TOUCHPADID" "libinput Natural Scrolling Enabled" 0
xinput set-prop "$TOUCHPADID" "libinput Disable While Typing Enabled" 1
xinput set-prop "$TOUCHPADID" "libinput Scroll Method Enabled" 1, 0, 0
xinput set-prop "$TOUCHPADID" "libinput Click Method Enabled" 1, 0
xinput set-prop "$TOUCHPADID" "libinput Middle Emulation Enabled" 1
xinput set-prop "$TOUCHPADID" "libinput Accel Speed" 0.000000
xinput set-prop "$TOUCHPADID" "libinput Accel Profile Enabled" 1, 0
xinput set-prop "$TOUCHPADID" "libinput Horizontal Scroll Enabled" 1




### Load keyboard layout and special keys
#########################################

if [[ -x "$(command -v setxkbmap)" ]]; then
    if [[ ! -f ~/.xlayout ]]; then
        printf "#!/bin/sh\nsetxkbmap -layout us\n" > ~/.xlayout
        chmod 755 ~/.xlayout
    fi
    ~/.xlayout
fi

if [[ -x "$(command -v xmodmap)" && -f ~/.Xmodmap ]]; then
    xmodmap ~/.Xmodmap
fi




### Load screen temperature
###########################

if [[ -x "$(command -v sct)" ]]; then
    if [[ ! -f ~/.xtemp ]]; then
        printf "#!/bin/sh\nsct 6500\n" > ~/.xtemp
        chmod 755 ~/.xtemp
    fi
    ~/.xtemp
fi




### Load mouse pointer
######################

xsetroot -cursor_name arrow
