#!/usr/bin/env bash

# XDG autostart, loginctl lock-session, applets
[[ -x "$(command -v dex)" ]] && dex --autostart --environment i3 &
[[ -x "$(command -v lxpolkit)" ]] && lxpolkit &
[[ -x "$(command -v nm-applet)" ]] && nm-applet &
[[ -x "$(command -v blueman-applet)" ]] && blueman-applet &
[[ -x "$(command -v flameshot)" ]] && flameshot &
[[ -x "$(command -v xautolock)" ]] && xautolock -time 15 -locker slock &
