#!/usr/bin/env bash

# load keyboard layout
if [[ -x "$(command -v setxkbmap)" ]]; then
    if [[ ! -f ~/.layout ]]; then
        printf "#!/bin/sh\nsetxkbmap -layout us\n" > ~/.layout
        chmod 755 ~/.layout
    fi
    ~/.layout
fi

# set special keys
if [[ -x "$(command -v xmodmap)" && -f ~/.Xmodmap ]]; then
    xmodmap ~/.Xmodmap
fi
