#!/usr/bin/env bash


[[ "$*" == "" ]] && exit 1

_no_preview () {
    echo "                                "
    echo "  ┌──────────────────────────┐  "
    echo "  │  Sorry mate, can't find  │  "
    echo "  │  any bloody man page.    │  "
    echo "  └───┬──────────────────────┘  "
    echo "      │                         "
    echo "      │      (\_/)              "
    echo "      └───── (O.o)              "
    echo "             (> <)              "
    echo "                                "
}

man "$*" 2>/dev/null || _no_preview
