#!/usr/bin/env bash

# This script spawns a scratchpad as long as i3 is running using i3-sensible-terminal
# It is very usefull if you want a terminal scratchpad always available.

# I do not use it anymore but if you do, add the following lines to
# your i3 config file in order to make the script work properly:
#
#   for_window [instance="scratchpad"] floating enable;
#              [instance="scratchpad"] resize set 800 600;
#              [instance="scratchpad"] move scratchpad
#
#   bindsym $mod+Shift+Return [instance="scratchpad"] scratchpad show;
#                             [instance="scratchpad"] move position center


while pgrep -x "i3"; do
    i3-sensible-terminal -T SCRATCHPAD -e tmux &
    wait $!
done
