#!/usr/bin/env bash


source $HOME/.xinput.bash

# more touchpad properties listed at
# `xinput list-props "$TOUCHPADID"`
xinput set-prop "$TOUCHPADID" "libinput Tapping Enabled" 1
xinput set-prop "$TOUCHPADID" "libinput Tapping Drag Enabled" 1
xinput set-prop "$TOUCHPADID" "libinput Natural Scrolling Enabled" 0
xinput set-prop "$TOUCHPADID" "libinput Disable While Typing Enabled" 1
xinput set-prop "$TOUCHPADID" "libinput Scroll Method Enabled" 1, 0, 0
xinput set-prop "$TOUCHPADID" "libinput Click Method Enabled" 1, 0
xinput set-prop "$TOUCHPADID" "libinput Middle Emulation Enabled" 1
xinput set-prop "$TOUCHPADID" "libinput Accel Speed" 0.000000
xinput set-prop "$TOUCHPADID" "libinput Accel Profile Enabled" 1, 0
xinput set-prop "$TOUCHPADID" "libinput Horizontal Scroll Enabled" 1
