#!/usr/bin/env bash

# This script search all opened windows and uses fzf to select one of them.
# It is intended to be used as such: i3-sensible-terminal -T __fuzzy__ -e i3windows


[[ -x "$(command -v wmctrl)" && -x "$(command -v fzf)" ]] || exit 1
WINTOGO=$(wmctrl -d | awk '{print $1, $NF}' | while read -r WSNUM WSNAME; do wmctrl -l | \
        grep -v __i3scratchpad__ | grep -v __800x600__ | grep -v __600x200__ | grep -w "$WSNUM" | \
        awk -v WSNAME="$WSNAME" '{ $2=$3=""; $1=" "$1; sub(/  /," "); print WSNAME, $0 }'; done | sort -V | \
        fzf --prompt='i3windows > ' --height 100% --margin 0% --reverse --info=hidden --header-first)
[[ -n "$WINTOGO" ]] || exit 1

echo "$WINTOGO" | awk '{print $2}' | xargs -I{} wmctrl -i -a {}


# few sorting alternatives:
# ... | sort -k1n | ...
# ... | sort -n -k1.1 | ...
# ... | sort -V | ...
