#!/usr/bin/env bash

LIST="tail -n +2 /tmp/vim_fuzzy_buffers"
if [[ -x "$(command -v mess)" ]]; then
    FILE="$(${LIST} | fzf --ansi --preview 'mess {}' --preview-window 'right,70%,border-left' `
            `--bind ctrl-d:preview-half-page-down,ctrl-u:preview-half-page-up --prompt="BUFFERS > " `
            `--height 100% --reverse --info=hidden --header-first)"
else
    FILE="$(${LIST} | fzf --ansi --preview 'less {}' --preview-window 'right,70%,border-left' `
            `--bind ctrl-d:preview-half-page-down,ctrl-u:preview-half-page-up --prompt="BUFFERS > " `
            `--height 100% --reverse --info=hidden --header-first)"
fi

[[ -z "$FILE" ]] && exit 1
echo "${FILE}" > /tmp/vim_fuzzy_current_file
